# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(950, 746)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.packetsList = QtGui.QTreeWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.packetsList.setFont(font)
        self.packetsList.setMouseTracking(True)
        self.packetsList.setStyleSheet(_fromUtf8("font: 11pt \"Cantarell\";\n"
"background-color: rgb(255, 245, 202);\n"
"selection-background-color: rgb(199, 199, 199);\n"
""))
        self.packetsList.setRootIsDecorated(False)
        self.packetsList.setItemsExpandable(True)
        self.packetsList.setAnimated(True)
        self.packetsList.setColumnCount(6)
        self.packetsList.setObjectName(_fromUtf8("packetsList"))
        self.packetsList.header().setVisible(True)
        self.packetsList.header().setDefaultSectionSize(150)
        self.packetsList.header().setMinimumSectionSize(150)
        self.verticalLayout.addWidget(self.packetsList)
        self.packetDetail = QtGui.QTabWidget(self.centralwidget)
        self.packetDetail.setMaximumSize(QtCore.QSize(16777215, 400))
        self.packetDetail.setTabPosition(QtGui.QTabWidget.North)
        self.packetDetail.setTabShape(QtGui.QTabWidget.Rounded)
        self.packetDetail.setObjectName(_fromUtf8("packetDetail"))
        self.tab_packet = QtGui.QWidget()
        self.tab_packet.setStyleSheet(_fromUtf8(""))
        self.tab_packet.setObjectName(_fromUtf8("tab_packet"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_packet)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tab_packet_hexdump = QtGui.QTextBrowser(self.tab_packet)
        self.tab_packet_hexdump.setStyleSheet(_fromUtf8("font: 75 12pt \"Courier 10 Pitch\";\n"
"background-color: rgb(255, 246, 239);\n"
"color: rgb(255, 85, 0);"))
        self.tab_packet_hexdump.setObjectName(_fromUtf8("tab_packet_hexdump"))
        self.gridLayout_4.addWidget(self.tab_packet_hexdump, 0, 0, 1, 1)
        self.packetDetail.addTab(self.tab_packet, _fromUtf8(""))

        self.tab_reassembling = QtGui.QWidget()
        self.tab_reassembling.setStyleSheet(_fromUtf8(""))
        self.tab_reassembling.setObjectName(_fromUtf8("tab_reassembling"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_reassembling)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tab_reassembling_hexdump = QtGui.QTextBrowser(self.tab_reassembling)
        self.tab_reassembling_hexdump.setStyleSheet(_fromUtf8("font: 75 12pt \"Courier 10 Pitch\";\n"
"background-color: rgb(255, 246, 239);\n"
"color: rgb(255, 85, 0);"))
        self.tab_reassembling_hexdump.setObjectName(_fromUtf8("tab_reassembling_hexdump"))
        self.gridLayout_8.addWidget(self.tab_reassembling_hexdump, 0, 0, 1, 1)
        self.packetDetail.addTab(self.tab_reassembling, _fromUtf8(""))


        self.tab_ethernet = QtGui.QWidget()
        self.tab_ethernet.setObjectName(_fromUtf8("tab_ethernet"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_ethernet)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tab_ethernet_list = QtGui.QTreeWidget(self.tab_ethernet)
        self.tab_ethernet_list.setStyleSheet(_fromUtf8("font: 11pt \"Cantarell\";\n"
"background-color: rgb(255, 246, 239);\n"
"color: rgb(0, 0, 127);"))
        self.tab_ethernet_list.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tab_ethernet_list.setRootIsDecorated(False)
        self.tab_ethernet_list.setObjectName(_fromUtf8("tab_ethernet_list"))
        self.tab_ethernet_list.header().setVisible(False)
        self.tab_ethernet_list.header().setDefaultSectionSize(200)
        self.tab_ethernet_list.header().setMinimumSectionSize(200)
        self.gridLayout_6.addWidget(self.tab_ethernet_list, 0, 0, 1, 1)
        self.packetDetail.addTab(self.tab_ethernet, _fromUtf8(""))
        self.tab_ip = QtGui.QWidget()
        self.tab_ip.setObjectName(_fromUtf8("tab_ip"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_ip)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tab_ip_list = QtGui.QTreeWidget(self.tab_ip)
        self.tab_ip_list.setStyleSheet(_fromUtf8("font: 11pt \"Cantarell\";\n"
"background-color: rgb(255, 246, 239);\n"
"color: rgb(0, 0, 127);"))
        self.tab_ip_list.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tab_ip_list.setRootIsDecorated(False)
        self.tab_ip_list.setAnimated(True)
        self.tab_ip_list.setObjectName(_fromUtf8("tab_ip_list"))
        self.tab_ip_list.header().setVisible(False)
        self.tab_ip_list.header().setDefaultSectionSize(200)
        self.tab_ip_list.header().setMinimumSectionSize(200)
        self.gridLayout_7.addWidget(self.tab_ip_list, 0, 0, 1, 1)
        self.packetDetail.addTab(self.tab_ip, _fromUtf8(""))
        self.tab_protocol = QtGui.QWidget()
        self.tab_protocol.setObjectName(_fromUtf8("tab_protocol"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_protocol)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tab_protocol_list = QtGui.QTreeWidget(self.tab_protocol)
        self.tab_protocol_list.setStyleSheet(_fromUtf8("font: 11pt \"Cantarell\";\n"
"background-color: rgb(255, 246, 239);\n"
"color: rgb(0, 0, 127);"))
        self.tab_protocol_list.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tab_protocol_list.setRootIsDecorated(False)
        self.tab_protocol_list.setAnimated(True)
        self.tab_protocol_list.setObjectName(_fromUtf8("tab_protocol_list"))
        self.tab_protocol_list.header().setVisible(False)
        self.tab_protocol_list.header().setDefaultSectionSize(200)
        self.tab_protocol_list.header().setMinimumSectionSize(200)
        self.gridLayout_5.addWidget(self.tab_protocol_list, 0, 0, 1, 1)
        self.packetDetail.addTab(self.tab_protocol, _fromUtf8(""))
        self.verticalLayout.addWidget(self.packetDetail)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label1 = QtGui.QLabel(self.groupBox)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.horizontalLayout_2.addWidget(self.label1)
        self.filtersInput = QtGui.QLineEdit(self.groupBox)
        self.filtersInput.setObjectName(_fromUtf8("filtersInput"))
        self.horizontalLayout_2.addWidget(self.filtersInput)
        self.toolButton = QtGui.QToolButton(self.groupBox)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.filtersApplyBtn = QtGui.QPushButton(self.groupBox)
        self.filtersApplyBtn.setObjectName(_fromUtf8("filtersApplyBtn"))
        self.horizontalLayout_2.addWidget(self.filtersApplyBtn)
        self.filtersInput.raise_()
        self.filtersApplyBtn.raise_()
        self.toolButton.raise_()
        self.label1.raise_()
        self.label2 = QtGui.QLabel(self.groupBox)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.horizontalLayout_2.addWidget(self.label2)
        self.srchInput = QtGui.QLineEdit(self.groupBox)
        self.srchInput.setObjectName(_fromUtf8("srchInput"))
        self.horizontalLayout_2.addWidget(self.srchInput)
        self.srchbackBtn = QtGui.QToolButton(self.groupBox)
        self.srchbackBtn.setObjectName(_fromUtf8("srchbackBtn"))
        self.horizontalLayout_2.addWidget(self.srchbackBtn)
        self.srchApplyBtn = QtGui.QPushButton(self.groupBox)
        self.srchApplyBtn.setObjectName(_fromUtf8("srchApplyBtn"))
        self.horizontalLayout_2.addWidget(self.srchApplyBtn)
        self.srchInput.raise_()
        self.srchApplyBtn.raise_()
        self.srchbackBtn.raise_()
        self.label2.raise_()
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 950, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuCapture = QtGui.QMenu(self.menuBar)
        self.menuCapture.setObjectName(_fromUtf8("menuCapture"))
        self.menuForging = QtGui.QMenu(self.menuBar)
        self.menuForging.setObjectName(_fromUtf8("menuForging"))
        self.menuSettings = QtGui.QMenu(self.menuBar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuFilter = QtGui.QMenu(self.menuBar)
        self.menuFilter.setObjectName(_fromUtf8("menuFilter"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon2)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionConvert_PDF = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_PDF.setIcon(icon3)
        self.actionConvert_PDF.setObjectName(_fromUtf8("actionConvert_PDF"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPerference = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPerference.setIcon(icon5)
        self.actionPerference.setObjectName(_fromUtf8("actionPerference"))
        self.actionInterface = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInterface.setIcon(icon6)
        self.actionInterface.setObjectName(_fromUtf8("actionInterface"))
        self.actionStart = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon7)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/stop2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon8)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionFilter = QtGui.QAction(MainWindow)
        self.actionFilter.setObjectName(_fromUtf8("actionFilter"))
        self.actionFRestore = QtGui.QAction(MainWindow)
        self.actionFRestore.setObjectName(_fromUtf8("actionFRestore"))
        self.actionPacket = QtGui.QAction(MainWindow)
        self.actionPacket.setObjectName(_fromUtf8("actionPacket"))
        self.actionClear = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("imgs/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon9)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionConvert_PDF)
        self.menuFile.addAction(self.actionQuit)
        self.menuCapture.addAction(self.actionStart)
        self.menuCapture.addAction(self.actionStop)
        self.menuCapture.addAction(self.actionClear)
        self.menuFilter.addAction(self.actionFilter)
        self.menuFilter.addAction(self.actionFRestore)
        self.menuSettings.addAction(self.actionInterface)
        self.menuSettings.addAction(self.actionPacket)
        self.menuSettings.addAction(self.actionPerference)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionManual)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuCapture.menuAction())
        self.menuBar.addAction(self.menuFilter.menuAction())
        self.menuBar.addAction(self.menuForging.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave_as)
        self.toolBar.addAction(self.actionConvert_PDF)
        self.toolBar.addAction(self.actionInterface)
        self.toolBar.addAction(self.actionPerference)
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        self.packetDetail.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "JKSniffer", None))
        self.packetsList.setSortingEnabled(True)
        self.packetsList.headerItem().setText(0, _translate("MainWindow", "Time", None))
        self.packetsList.headerItem().setText(1, _translate("MainWindow", "No.", None))
        self.packetsList.headerItem().setText(2, _translate("MainWindow", "Source", None))
        self.packetsList.headerItem().setText(3, _translate("MainWindow", "Destination", None))
        self.packetsList.headerItem().setText(4, _translate("MainWindow", "Info", None))
        self.packetsList.headerItem().setText(5, _translate("MainWindow", "Protocol", None))
        self.tab_packet_hexdump.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier 10 Pitch\'; font-size:12pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-weight:400; color:#ff5500;\">No packet selected</span></p></body></html>", None))
        self.packetDetail.setTabText(self.packetDetail.indexOf(self.tab_packet), _translate("MainWindow", "Packet", None))

        self.tab_reassembling_hexdump.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier 10 Pitch\'; font-size:12pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-weight:400; color:#ff5500;\">No packet selected</span></p></body></html>", None))
        self.packetDetail.setTabText(self.packetDetail.indexOf(self.tab_reassembling), _translate("MainWindow", "Reassembling", None))

        self.tab_ethernet_list.headerItem().setText(0, _translate("MainWindow", "Field name", None))
        self.tab_ethernet_list.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.packetDetail.setTabText(self.packetDetail.indexOf(self.tab_ethernet), _translate("MainWindow", "Ethernet", None))
        self.tab_ip_list.headerItem().setText(0, _translate("MainWindow", "Field name", None))
        self.tab_ip_list.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.packetDetail.setTabText(self.packetDetail.indexOf(self.tab_ip), _translate("MainWindow", "IP", None))
        self.tab_protocol_list.headerItem().setText(0, _translate("MainWindow", "Field name", None))
        self.tab_protocol_list.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.packetDetail.setTabText(self.packetDetail.indexOf(self.tab_protocol), _translate("MainWindow", "Protocol", None))
        self.label1.setText(_translate("MainWindow", "Filter :", None))
        self.filtersInput.setToolTip(_translate("MainWindow", "LayerType/Field/Value, LayerType/Field/Value, ....", None))
        self.filtersInput.setStatusTip(_translate("MainWindow", "LayerType/Field/Value, LayerType/Field/Value, ....", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.filtersApplyBtn.setText(_translate("MainWindow", "Apply", None))
        self.label2.setText(_translate("MainWindow", "Search :", None))
        self.srchInput.setToolTip(_translate("MainWindow", "LayerType/Field/Value, LayerType/Field/Value, ....", None))
        self.srchInput.setStatusTip(_translate("MainWindow", "LayerType/Field/Value, LayerType/Field/Value, ....", None))
        self.srchbackBtn.setText(_translate("MainWindow", "Back", None))
        self.srchApplyBtn.setText(_translate("MainWindow", "Apply", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuCapture.setTitle(_translate("MainWindow", "Capture", None))
        self.menuForging.setTitle(_translate("MainWindow", "Forging", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionConvert_PDF.setText(_translate("MainWindow", "Convert PDF", None))
        self.actionConvert_PDF.setShortcut(_translate("MainWindow", "F1", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionPerference.setText(_translate("MainWindow", "Perference", None))
        self.actionInterface.setText(_translate("MainWindow", "Interface", None))
        self.actionStart.setText(_translate("MainWindow", "Start ", None))
        self.actionStart.setShortcut(_translate("MainWindow", "F5", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionStop.setShortcut(_translate("MainWindow", "F5", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionManual.setText(_translate("MainWindow", "Manual", None))
        self.actionFilter.setText(_translate("MainWindow", "Filter", None))
        self.actionFRestore.setText(_translate("MainWindow", "Restore", None))
        self.actionPacket.setText(_translate("MainWindow", "Packet", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear", None))

